### ISSUE TITLE
Reporte de practica

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-aguita-de-limon#1]
[Practica 4 y 5 - ITI.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-aguita-de-limon/files/15204850/Practica.4.y.5.-.ITI.pdf)

**Comment by Luz1727** [comment]
buen trabajo 19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
